theme: osuny
_merge: deep
outputs:
  page:
  - html
  section:
  - html
  - rss
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: ''
    footer: ''
pagination:
  pagerSize: 108